BonVoyage_TravelAgency/Controllers/FAQController.cs
using BonVoyage.BLL.DTOs;
using BonVoyage.BLL.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BonVoyage_TravelAgency.Controllers
{
    public class FAQController : BaseController
    {
        private readonly IFAQService _faqService;

        public FAQController(IFAQService faqService)
        {
            _faqService = faqService;
        }

        public async Task<IActionResult> Index()
        {
            var faqs = await _faqService.GetAllFAQsAsync();
            return View(faqs);
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            FAQDTO faq = new FAQDTO();
            if (id.HasValue)
            {
                faq = await _faqService.GetFAQByIdAsync(id.Value);
                if (faq == null)
                {
                    return NotFound();
                }
            }
            return View(faq);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(FAQDTO faq)
        {
            if (ModelState.IsValid)
            {
                if (faq.FAQId == 0)
                {
                    await _faqService.CreateFAQAsync(faq);
                }
                else
                {
                    await _faqService.UpdateFAQAsync(faq);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(faq);
        }


        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var faq = await _faqService.GetFAQByIdAsync(id);
            if (faq == null)
            {
                return Json(new { success = false, message = "FAQ not found!" });
            }

            await _faqService.DeleteFAQAsync(id);
            return Json(new { success = true, message = "FAQ deleted successfully!" });
        }

    }
}

BonVoyage_TravelAgency/Controllers/GuideController.cs
using Microsoft.AspNetCore.Mvc;

namespace BonVoyage_TravelAgency.Controllers
{
    public class GuideController : BaseController
    {
        public IActionResult WhereToGo()
        {
            return View();
        }

        public IActionResult TravelInsurance()
        {
            return View();
        }

        public IActionResult TravelNews()
        {
            return View();
        }

        public IActionResult TipsForTourists()
        {
            return View();
        }

        public IActionResult CoronavirusTests()
        {
            return View();
        }
    }
}

BonVoyage_TravelAgency/Views/Shared/_Layout.cshtml
@using System.Globalization
@using BonVoyage_TravelAgency.Resources
@using static BonVoyage_TravelAgency.Resources.Resource
<!DOCTYPE html>
<html lang="@CultureInfo.CurrentUICulture.TwoLetterISOLanguageName">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BonVoyage_TravelAgency</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BonVoyage_TravelAgency.styles.css" asp-append-version="true" />    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="icon" type="image/x-icon" href="/images/favicon-removebg-preview.png">
</head>
<body>
    <header>        
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom" style="background-color: #158af0">
            <div class="container-fluid">
                <div class="logo">
                    <a href="#"><img src="~/images/BON_VOYAGE_Paris-removebg-preview.png" alt="Logo"></a>
                    <a class="navbar-brand size30 colorOrange" asp-area="" asp-controller="Home" asp-action="Index">BonVoyage TravelAgency</a>
                </div>                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>              
                <a class="navbar-brand size20 colorWhite" asp-area="" asp-controller="Home" asp-action="Preferences">My preferences</a>
                
                @if (Context.Session.GetString("UserName") == null)
                {
                    <a class="navbar-brand size20 colorWhite" asp-area="" asp-controller="Account" asp-action="Register">@Registration</a>                    
                    <a class="navbar-brand size20 colorWhite" asp-area="" asp-controller="Account" asp-action="Login">@Login</a>
                }
                else
                {                                   
                    <span class="navbar-brand size20">Hello, @Context.Session.GetString("UserName")</span>
                    <a class="navbar-brand size20 colorWhite" href="@Url.Action("Profile", "Account")">Profile</a>
                    <a class="navbar-brand size20 colorWhite" asp-area="" asp-controller="Account" asp-action="Logout">@Logout</a>
                    <a href="/Chat/Index" class="btn size20 colorWhite">@Go_to_Chat_Room</a>
                }          
               
                
                <div class="language-selector">
                    <form action="@Url.Action("ChangeCulture", "Home")" method="post" id="language-form">
                        <input type="hidden" name="lang" id="selected-lang">
                        <button class="lang-btn">
                            <span id="current-lang">@CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.ToUpper()</span>
                            <i class="arrow-down"></i> <!-- иконка стрелки -->
                        </button>
                        <ul class="lang-dropdown">
                            <li><button type="submit" onclick="document.getElementById('selected-lang').value='en';">EN</button></li>
                            <li><button type="submit" onclick="document.getElementById('selected-lang').value='fr';">FR</button></li>
                            <li><button type="submit" onclick="document.getElementById('selected-lang').value='sk';">SK</button></li>
                            <li><button type="submit" onclick="document.getElementById('selected-lang').value='uk';">UK</button></li>
                        </ul>
                    </form>
                </div>


            </div>
        </nav>
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarSupportedContent" style="display:flex; justify-content:space-evenly">
                <ul class="navbar-nav mr-auto">                    
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle colorBlue size20" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @Countries
                        </a>
                        <div class="dropdown-menu size18" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item colorBlue" href="#">@Tours_to_Turkey</a>
                            <a class="dropdown-item colorBlue" href="#">@Tours_to_Egypt</a>
                            <a class="dropdown-item colorBlue" href="#">@Tours_to_Greece</a>
                            <a class="dropdown-item colorBlue" href="#">@Tours_to_Spain</a>
                            <a class="dropdown-item colorBlue" href="#">@Tours_to_Croitia</a>
                            <a href="~/Index.html?userName=@Context.Session.GetString("UserName")">All countries of the world</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle colorBlue size20" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @Search_Tours
                        </a>
                        <div class="dropdown-menu size18" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item colorBlue" href="#">@Package_tours</a>
                            <a class="dropdown-item colorBlue" href="#">@Summer_tours</a>
                            <a class="dropdown-item colorBlue" href="#">@Winter_tours</a>
                            <a class="dropdown-item colorBlue" href="#">@Spring_tours</a>
                            <a class="dropdown-item colorBlue" href="#">@New_year_tours</a>
                            <a class="dropdown-item colorBlue" href="#">@Ski_tours</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle colorBlue size20" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @Charters
                        </a>
                        <div class="dropdown-menu size18" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item colorBlue" href="#"> @Charters_to_Turkey</a>
                            <a class="dropdown-item colorBlue" href="#"> @Charters_to_Egypt</a>
                            <a class="dropdown-item colorBlue" href="#"> @Charters_to_Greece</a>
                            <a class="dropdown-item colorBlue" href="#"> @Charters_to_Montenegro</a>
                            <a class="dropdown-item colorBlue" href="#"> @Charters_to_Bulgaria</a>
                            <a class="dropdown-item colorBlue" href="#">@All_charter_flights</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle colorBlue size20" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @Guide
                        </a>
                        <div class="dropdown-menu size18" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item colorBlue" href="@Url.Action("WhereToGo", "Guide")">@Where_to_go_for_a_tourist</a>
                            <a class="dropdown-item colorBlue" href="@Url.Action("TravelInsurance", "Guide")">@Travel_insurance</a>
                            <a class="dropdown-item colorBlue" href="@Url.Action("TravelNews", "Guide")">@Travel_news</a>
                            <a class="dropdown-item colorBlue" href="@Url.Action("TipsForTourists", "Guide")">@Tips_for_tourists</a>
                            <a class="dropdown-item colorBlue" href="@Url.Action("CoronavirusTests", "Guide")">@Coronavirus_tests</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle colorBlue size20" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @About_BonVoyage
                        </a>
                        <div class="dropdown-menu size18" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item colorBlue" href="https://localhost:7079/Home/AboutUs">@About_Bon_Voyage_Company</a>
                            <a class="dropdown-item colorBlue" href="#">@Reviews_from_tourists</a>
                            <a class="dropdown-item colorBlue" href="https://localhost:7079/FAQ">@FAQ</a>
                            <a class="dropdown-item colorBlue" href="#">@Why_do_people_trust_us</a>
                            <a class="dropdown-item colorBlue" href="#">@How_to_book_a_tour</a>
                            <a class="dropdown-item colorBlue" href="#">@How_to_pay_for_the_tour</a>
                            <a class="dropdown-item colorBlue" href="#">@Refund</a>
                            <a class="dropdown-item colorBlue" href="#">@Legal_information</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle colorBlue size20" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @Where_to_buy
                        </a>
                        <div class="dropdown-menu size18" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item colorBlue" href="#">@Office_addresses</a>
                            <a class="dropdown-item colorBlue" href="#">@Travel_agencies_in_Paris</a>
                            <a class="dropdown-item colorBlue" href="#">@Travel_agencies_in_Lyon</a>
                            <a class="dropdown-item colorBlue" href="#">@Travel_agencies_in_Nice</a>
                            <a class="dropdown-item colorBlue" href="#">@Travel_agencies_in_Bordeaux</a>
                            <a class="dropdown-item colorBlue" href="#">@Travel_agencies_in_Marseilles</a>
                        </div>
                    </li>  
                    <li class="nav-item dropdown">
                        @if (Context.Session.GetString("UserName") == "Admin")
                        {
                        <a class="nav-link dropdown-toggle colorBlue size20" href="https://localhost:7079/Booking/Index" id="navbarDropdown">
                            Bookings(for Admin)
                        </a>
                        }
                    </li>
                </ul>               
            </div>           
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="containerPrivacy size18">
            &copy; 2024 - BonVoyage_TravelAgency - <a asp-area="" asp-controller="Home" asp-action="Privacy">@Privacy </a> |
            <a class="size18" asp-area="" asp-controller="FAQ" asp-action="Index"> @FAQ</a> |
            <a class="size18" asp-area="" asp-controller="Home" asp-action="Contacts"> @Contacts</a> |
            <a class="size18" asp-area="" asp-controller="Home" asp-action="AboutUs"> @About_Us</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.3.6/dist/sweetalert2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>